# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aec5f5d0faffb888261f17ce88407a1e9c499fa3766bddec05b3768e2d1046a7a4ec28e19d8be3de3aa13fd59594dba5d4214b532bb887edf81f7ca85b3e2ea

test:
  secret_key_base: 56fb029cad56d5ce692abf413b8ba7b0a00b6b56c6e00223413d9cdb4c1a14c5b8c8f3417031829cb06cf5d2511cb196bcc57419969707e0e96ad853232bd0e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
